name: drapyy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2 # sdk: ^3.5.3



dependencies:
  flutter:
    sdk: flutter
  # /////////// Shared Preferences //////////////////
  #  shared_preferences: any
  http: ^0.13.3
  shared_preferences: any
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.12.0  # Check for the latest version
  flutter_xlider: ^3.0.0
  webview_flutter: ^4.2.4
  fluttertoast: any
  intl: ^0.18.0
  google_maps_flutter: ^2.2.2
  geolocator: 13.0.2
  url_launcher: ^6.1.10 # Or the latest available version
  permission_handler: any
  flutter_svg: any

  shimmer: ^3.0.0
  media_store_plus: ^0.1.3
  device_info_plus: ^10.1.0
  get: any

  flutter_polyline_points: any
  event_bus: any
  dropdown_search: ^5.0.6
  getwidget: ^4.0.0
  #flutter_local_notifications: any

  path_provider: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/


  fonts:

    - family: Baskerville
      fonts:
        - asset: assets/fonts/baskerville_bold.otf

    - family: Gotham Pro
      fonts:
        - asset: assets/fonts/gotham_pro_bold.ttf
        - asset: assets/fonts/gothamproregular.ttf

    - family: Lavos Handy
      fonts:
        - asset: assets/fonts/lavoshandy_regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
        - asset: assets/fonts/roboto_medium.ttf
        - asset: assets/fonts/roboto_regular.ttf

    - family: Tekton Pro
      fonts:
        - asset: assets/fonts/tektonpro_bold.otf
        - asset: assets/fonts/tektonpro_boldcond.otf
        - asset: assets/fonts/tektonpro_boldcondobl.otf
        - asset: assets/fonts/tektonpro_boldext.otf
        - asset: assets/fonts/tektonpro_boldextobl.otf
        - asset: assets/fonts/tektonpro_boldobl.otf
        - asset: assets/fonts/tektonpro_cond.otf
        - asset: assets/fonts/tektonpro_condobl.otf
        - asset: assets/fonts/tektonpro_ext.otf
        - asset: assets/fonts/tektonpro_extobl.otf
        - asset: assets/fonts/tektonpro_light.otf
        - asset: assets/fonts/tektonpro_lightcond.otf
        - asset: assets/fonts/tektonpro_lightcondobl.otf
        - asset: assets/fonts/tektonpro_lightext.otf
        - asset: assets/fonts/tektonpro_lightextobl.otf
        - asset: assets/fonts/tektonpro_lightobl.otf
        - asset: assets/fonts/tektonpro_regular.otf


